### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by EzequielVilla** [alexbal12/dwf-m6-desafio-final#1]
Buenas! Te quedo muy bien la pagina, funciona todo perfectamente, incluso sali y volvi a conectarme a la misma sala con los dos jugadores y recupere el score. La documentacion de postman me sirvio mucho para ir interpretando cada endpoint del backend.
Felicitaciones che, buen laburo!

**Comment by alexbalieiro** [comment]
Muchísimas gracias por la devolución, costó pero se cumplió con el objetivo, nos estamos viendo!
